name: Build Wheels

on: [push, workflow_dispatch] 

env:
  CIBW_SKIP: cp36-* cp37* pp* *-musllinux* cp312-macosx*

jobs:
  build_wheels:
    name: Build wheels on ${{matrix.arch}} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
        arch: [auto]

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        if:  ${{ matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v2


      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        # with:
        #   cmake-version: '3.16.x'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        # to supply options, put them in 'env', like:
        env:
          CIBW_BEFORE_BUILD: git submodule init && git submodule update && pip install "cmake>=3.30.2" && pip install cython numpy scikit-build
          CPPFLAGS: -I/usr/local/opt/zlib/include
          LDFLAGS: -L/usr/local/opt/zlib/lib
          CIBW_ARCHS_MACOS: "x86_64"
          CIBW_ARCHS_LINUX: "auto"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
